[package]
name = "create_festl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
indicatif = "0.17.8"
regex = "1.10.4"
reqwest = { version ="0.12.3", features = ["blocking"]}
